name: pacer
description: A new Flutter project.
publish_to: "none"
version: 0.1.0
#project migrated :pacer
environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  geocoding: ^2.1.1
  geolocator: ^10.1.0
  google_maps_flutter: ^2.5.0
  app_settings: ^5.1.1
  animated_snack_bar: ^0.4.0
  flutter_staggered_animations: ^1.1.1
  flutter_vector_icons: ^2.0.0
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.2
  share_plus: ^7.2.1
  flutter_compass: ^0.8.0
  alxgration_speedometer: ^0.0.2
  permission_handler: ^11.1.0
  http: ^1.1.2
  cloud_firestore: ^4.13.6
  firebase_core: ^2.24.2
  provider: ^6.1.1
  flutter_material_pickers: ^3.6.0
  uuid: ^4.2.2
  pedometer: ^4.0.1
  geodesy:
  hive: ^2.2.3
  path_provider: ^2.1.1
  connectivity_plus: ^5.0.2
  percent_indicator: ^4.2.3
  syncfusion_flutter_charts: ^23.2.7
  blurrycontainer: ^1.0.2
  flutter_background_service: ^5.0.5
  flutter_background_service_android: ^6.2.2
  flutter_polyline_points: ^2.0.0
  ionicons: ^0.2.2
  firebase_auth: ^4.15.3
  google_sign_in: ^6.2.1
  firebase_messaging: ^14.7.9
  sign_in_with_apple: ^5.0.0
  mockito: ^5.4.4
  flutter_dotenv: ^5.1.0
  firebase_auth_mocks: ^0.13.0
  google_sign_in_mocks: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  fonts:
    - family: RobotoRound
      fonts:
        - asset: assets/font/roboto_round.ttf
    - family: Weather
      fonts:
        - asset: assets/font/weather.ttf

  assets:
    - assets/drawable/
    - .env
